name             'typo3'
maintainer       'YOUR_NAME'
maintainer_email 'cookbooks@mojocode.de'
license          'Apache 2.0'
description      'Installs/Configures typo3'
long_description 'Installs/Configures typo3'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'timezone-ii'
depends 'hostnames'
depends 'locales'
depends 'ssh_known_hosts'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'systemd'
depends 'database'
depends 'tar'
